package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"mybanks-api/ent"
	"mybanks-api/ent/banktranslation"
	"strconv"
)

// Translation is the resolver for the translation field.
func (r *bankResolver) Translation(ctx context.Context, obj *ent.Bank, locale string) (*ent.BankTranslation, error) {

	translation, err := r.Client.BankTranslation.
		Query().
		Where(
			banktranslation.BankID(obj.ID),
			banktranslation.Locale(locale),
		).
		Only(ctx)

	if ent.IsNotFound(err) {
		return nil, nil
	}

	return translation, err
}

// Bank is the resolver for the bank field.
func (r *queryResolver) Bank(ctx context.Context, id string) (*ent.Bank, error) {
	iId, _ := strconv.Atoi(id)
	return r.Client.Bank.Get(ctx, iId)
}
