package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"
	"mybanks-api/ent"
)

// Bank возвращает вложенные данные по валютам и предложениям.
func (r *queryResolver) Offers(ctx context.Context, obj *ent.Bank) ([]*ent.Offer, error) {
	return obj.QueryOffers().All(ctx)
}

func (r *queryResolver) CurrencyRates(ctx context.Context, obj *ent.Bank) ([]*ent.CurrencyRate, error) {
	return obj.QueryCurrencyRates().All(ctx)
}

// CreateBank is the resolver for the createBank field.
func (r *mutationResolver) CreateBank(ctx context.Context, name string, country string) (*ent.Bank, error) {
	panic(fmt.Errorf("not implemented: CreateBank - createBank"))
}

// Banks is the resolver for the banks field.
func (r *queryResolver) Banks(ctx context.Context) ([]*ent.Bank, error) {
	return r.Client.Bank.Query().
		WithOffers().        // загружаем связанные offers
		WithCurrencyRates(). // загружаем связанные currencyRates
		All(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
