// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateBankRes interface {
	createBankRes()
}

type CreateCurrencyRateRes interface {
	createCurrencyRateRes()
}

type CreateOfferRes interface {
	createOfferRes()
}

type DeleteBankRes interface {
	deleteBankRes()
}

type DeleteCurrencyRateRes interface {
	deleteCurrencyRateRes()
}

type DeleteOfferRes interface {
	deleteOfferRes()
}

type ListBankCurrencyRatesRes interface {
	listBankCurrencyRatesRes()
}

type ListBankOffersRes interface {
	listBankOffersRes()
}

type ListBankRes interface {
	listBankRes()
}

type ListCurrencyRateRes interface {
	listCurrencyRateRes()
}

type ListOfferRes interface {
	listOfferRes()
}

type ReadBankRes interface {
	readBankRes()
}

type ReadCurrencyRateBankRes interface {
	readCurrencyRateBankRes()
}

type ReadCurrencyRateRes interface {
	readCurrencyRateRes()
}

type ReadOfferBankRes interface {
	readOfferBankRes()
}

type ReadOfferRes interface {
	readOfferRes()
}

type UpdateBankRes interface {
	updateBankRes()
}

type UpdateCurrencyRateRes interface {
	updateCurrencyRateRes()
}

type UpdateOfferRes interface {
	updateOfferRes()
}
