// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/BankCreate
type BankCreate struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *BankCreate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *BankCreate) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *BankCreate) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *BankCreate) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *BankCreate) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *BankCreate) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *BankCreate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *BankCreate) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *BankCreate) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *BankCreate) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *BankCreate) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *BankCreate) SetTest(val OptString) {
	s.Test = val
}

func (*BankCreate) createBankRes() {}

// Ref: #/components/schemas/Bank_CurrencyRatesList
type BankCurrencyRatesList struct {
	ID       int     `json:"id"`
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
}

// GetID returns the value of ID.
func (s *BankCurrencyRatesList) GetID() int {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *BankCurrencyRatesList) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *BankCurrencyRatesList) GetRate() float64 {
	return s.Rate
}

// SetID sets the value of ID.
func (s *BankCurrencyRatesList) SetID(val int) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *BankCurrencyRatesList) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *BankCurrencyRatesList) SetRate(val float64) {
	s.Rate = val
}

// Ref: #/components/schemas/BankList
type BankList struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *BankList) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *BankList) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *BankList) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *BankList) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *BankList) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *BankList) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *BankList) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *BankList) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *BankList) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *BankList) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *BankList) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *BankList) SetTest(val OptString) {
	s.Test = val
}

// Ref: #/components/schemas/Bank_OffersList
type BankOffersList struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
}

// GetID returns the value of ID.
func (s *BankOffersList) GetID() int {
	return s.ID
}

// GetType returns the value of Type.
func (s *BankOffersList) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *BankOffersList) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *BankOffersList) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *BankOffersList) SetID(val int) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *BankOffersList) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *BankOffersList) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *BankOffersList) SetLink(val string) {
	s.Link = val
}

// Ref: #/components/schemas/BankRead
type BankRead struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *BankRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *BankRead) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *BankRead) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *BankRead) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *BankRead) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *BankRead) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *BankRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *BankRead) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *BankRead) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *BankRead) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *BankRead) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *BankRead) SetTest(val OptString) {
	s.Test = val
}

func (*BankRead) readBankRes() {}

// Ref: #/components/schemas/BankUpdate
type BankUpdate struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *BankUpdate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *BankUpdate) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *BankUpdate) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *BankUpdate) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *BankUpdate) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *BankUpdate) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *BankUpdate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *BankUpdate) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *BankUpdate) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *BankUpdate) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *BankUpdate) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *BankUpdate) SetTest(val OptString) {
	s.Test = val
}

func (*BankUpdate) updateBankRes() {}

type CreateBankReq struct {
	Name          string    `json:"name"`
	Country       string    `json:"country"`
	Website       OptString `json:"website"`
	LogoURL       OptString `json:"logo_url"`
	Test          OptString `json:"test"`
	CurrencyRates []int     `json:"currency_rates"`
	Offers        []int     `json:"offers"`
}

// GetName returns the value of Name.
func (s *CreateBankReq) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *CreateBankReq) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *CreateBankReq) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *CreateBankReq) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *CreateBankReq) GetTest() OptString {
	return s.Test
}

// GetCurrencyRates returns the value of CurrencyRates.
func (s *CreateBankReq) GetCurrencyRates() []int {
	return s.CurrencyRates
}

// GetOffers returns the value of Offers.
func (s *CreateBankReq) GetOffers() []int {
	return s.Offers
}

// SetName sets the value of Name.
func (s *CreateBankReq) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *CreateBankReq) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *CreateBankReq) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *CreateBankReq) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *CreateBankReq) SetTest(val OptString) {
	s.Test = val
}

// SetCurrencyRates sets the value of CurrencyRates.
func (s *CreateBankReq) SetCurrencyRates(val []int) {
	s.CurrencyRates = val
}

// SetOffers sets the value of Offers.
func (s *CreateBankReq) SetOffers(val []int) {
	s.Offers = val
}

type CreateCurrencyRateReq struct {
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
	Bank     int     `json:"bank"`
}

// GetCurrency returns the value of Currency.
func (s *CreateCurrencyRateReq) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *CreateCurrencyRateReq) GetRate() float64 {
	return s.Rate
}

// GetBank returns the value of Bank.
func (s *CreateCurrencyRateReq) GetBank() int {
	return s.Bank
}

// SetCurrency sets the value of Currency.
func (s *CreateCurrencyRateReq) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *CreateCurrencyRateReq) SetRate(val float64) {
	s.Rate = val
}

// SetBank sets the value of Bank.
func (s *CreateCurrencyRateReq) SetBank(val int) {
	s.Bank = val
}

type CreateOfferReq struct {
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
	Bank        int    `json:"bank"`
}

// GetType returns the value of Type.
func (s *CreateOfferReq) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *CreateOfferReq) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *CreateOfferReq) GetLink() string {
	return s.Link
}

// GetBank returns the value of Bank.
func (s *CreateOfferReq) GetBank() int {
	return s.Bank
}

// SetType sets the value of Type.
func (s *CreateOfferReq) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *CreateOfferReq) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *CreateOfferReq) SetLink(val string) {
	s.Link = val
}

// SetBank sets the value of Bank.
func (s *CreateOfferReq) SetBank(val int) {
	s.Bank = val
}

// Ref: #/components/schemas/CurrencyRate_BankRead
type CurrencyRateBankRead struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *CurrencyRateBankRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *CurrencyRateBankRead) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *CurrencyRateBankRead) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *CurrencyRateBankRead) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *CurrencyRateBankRead) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *CurrencyRateBankRead) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *CurrencyRateBankRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CurrencyRateBankRead) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *CurrencyRateBankRead) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *CurrencyRateBankRead) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *CurrencyRateBankRead) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *CurrencyRateBankRead) SetTest(val OptString) {
	s.Test = val
}

func (*CurrencyRateBankRead) readCurrencyRateBankRes() {}

// Ref: #/components/schemas/CurrencyRateCreate
type CurrencyRateCreate struct {
	ID       int     `json:"id"`
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
}

// GetID returns the value of ID.
func (s *CurrencyRateCreate) GetID() int {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *CurrencyRateCreate) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *CurrencyRateCreate) GetRate() float64 {
	return s.Rate
}

// SetID sets the value of ID.
func (s *CurrencyRateCreate) SetID(val int) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *CurrencyRateCreate) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *CurrencyRateCreate) SetRate(val float64) {
	s.Rate = val
}

func (*CurrencyRateCreate) createCurrencyRateRes() {}

// Ref: #/components/schemas/CurrencyRateList
type CurrencyRateList struct {
	ID       int     `json:"id"`
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
}

// GetID returns the value of ID.
func (s *CurrencyRateList) GetID() int {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *CurrencyRateList) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *CurrencyRateList) GetRate() float64 {
	return s.Rate
}

// SetID sets the value of ID.
func (s *CurrencyRateList) SetID(val int) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *CurrencyRateList) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *CurrencyRateList) SetRate(val float64) {
	s.Rate = val
}

// Ref: #/components/schemas/CurrencyRateRead
type CurrencyRateRead struct {
	ID       int     `json:"id"`
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
}

// GetID returns the value of ID.
func (s *CurrencyRateRead) GetID() int {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *CurrencyRateRead) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *CurrencyRateRead) GetRate() float64 {
	return s.Rate
}

// SetID sets the value of ID.
func (s *CurrencyRateRead) SetID(val int) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *CurrencyRateRead) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *CurrencyRateRead) SetRate(val float64) {
	s.Rate = val
}

func (*CurrencyRateRead) readCurrencyRateRes() {}

// Ref: #/components/schemas/CurrencyRateUpdate
type CurrencyRateUpdate struct {
	ID       int     `json:"id"`
	Currency string  `json:"currency"`
	Rate     float64 `json:"rate"`
}

// GetID returns the value of ID.
func (s *CurrencyRateUpdate) GetID() int {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *CurrencyRateUpdate) GetCurrency() string {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *CurrencyRateUpdate) GetRate() float64 {
	return s.Rate
}

// SetID sets the value of ID.
func (s *CurrencyRateUpdate) SetID(val int) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *CurrencyRateUpdate) SetCurrency(val string) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *CurrencyRateUpdate) SetRate(val float64) {
	s.Rate = val
}

func (*CurrencyRateUpdate) updateCurrencyRateRes() {}

// DeleteBankNoContent is response for DeleteBank operation.
type DeleteBankNoContent struct{}

func (*DeleteBankNoContent) deleteBankRes() {}

// DeleteCurrencyRateNoContent is response for DeleteCurrencyRate operation.
type DeleteCurrencyRateNoContent struct{}

func (*DeleteCurrencyRateNoContent) deleteCurrencyRateRes() {}

// DeleteOfferNoContent is response for DeleteOffer operation.
type DeleteOfferNoContent struct{}

func (*DeleteOfferNoContent) deleteOfferRes() {}

type ListBankCurrencyRatesOKApplicationJSON []BankCurrencyRatesList

func (*ListBankCurrencyRatesOKApplicationJSON) listBankCurrencyRatesRes() {}

type ListBankOKApplicationJSON []BankList

func (*ListBankOKApplicationJSON) listBankRes() {}

type ListBankOffersOKApplicationJSON []BankOffersList

func (*ListBankOffersOKApplicationJSON) listBankOffersRes() {}

type ListCurrencyRateOKApplicationJSON []CurrencyRateList

func (*ListCurrencyRateOKApplicationJSON) listCurrencyRateRes() {}

type ListOfferOKApplicationJSON []OfferList

func (*ListOfferOKApplicationJSON) listOfferRes() {}

// Ref: #/components/schemas/Offer_BankRead
type OfferBankRead struct {
	ID      int       `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Website OptString `json:"website"`
	LogoURL OptString `json:"logo_url"`
	Test    OptString `json:"test"`
}

// GetID returns the value of ID.
func (s *OfferBankRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *OfferBankRead) GetName() string {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *OfferBankRead) GetCountry() string {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *OfferBankRead) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *OfferBankRead) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *OfferBankRead) GetTest() OptString {
	return s.Test
}

// SetID sets the value of ID.
func (s *OfferBankRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *OfferBankRead) SetName(val string) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *OfferBankRead) SetCountry(val string) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *OfferBankRead) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *OfferBankRead) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *OfferBankRead) SetTest(val OptString) {
	s.Test = val
}

func (*OfferBankRead) readOfferBankRes() {}

// Ref: #/components/schemas/OfferCreate
type OfferCreate struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
}

// GetID returns the value of ID.
func (s *OfferCreate) GetID() int {
	return s.ID
}

// GetType returns the value of Type.
func (s *OfferCreate) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *OfferCreate) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *OfferCreate) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *OfferCreate) SetID(val int) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *OfferCreate) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *OfferCreate) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *OfferCreate) SetLink(val string) {
	s.Link = val
}

func (*OfferCreate) createOfferRes() {}

// Ref: #/components/schemas/OfferList
type OfferList struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
}

// GetID returns the value of ID.
func (s *OfferList) GetID() int {
	return s.ID
}

// GetType returns the value of Type.
func (s *OfferList) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *OfferList) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *OfferList) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *OfferList) SetID(val int) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *OfferList) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *OfferList) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *OfferList) SetLink(val string) {
	s.Link = val
}

// Ref: #/components/schemas/OfferRead
type OfferRead struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
}

// GetID returns the value of ID.
func (s *OfferRead) GetID() int {
	return s.ID
}

// GetType returns the value of Type.
func (s *OfferRead) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *OfferRead) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *OfferRead) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *OfferRead) SetID(val int) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *OfferRead) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *OfferRead) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *OfferRead) SetLink(val string) {
	s.Link = val
}

func (*OfferRead) readOfferRes() {}

// Ref: #/components/schemas/OfferUpdate
type OfferUpdate struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Link        string `json:"link"`
}

// GetID returns the value of ID.
func (s *OfferUpdate) GetID() int {
	return s.ID
}

// GetType returns the value of Type.
func (s *OfferUpdate) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *OfferUpdate) GetDescription() string {
	return s.Description
}

// GetLink returns the value of Link.
func (s *OfferUpdate) GetLink() string {
	return s.Link
}

// SetID sets the value of ID.
func (s *OfferUpdate) SetID(val int) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *OfferUpdate) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *OfferUpdate) SetDescription(val string) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *OfferUpdate) SetLink(val string) {
	s.Link = val
}

func (*OfferUpdate) updateOfferRes() {}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type R400 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R400) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R400) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R400) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R400) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R400) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R400) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R400) createBankRes()            {}
func (*R400) createCurrencyRateRes()    {}
func (*R400) createOfferRes()           {}
func (*R400) deleteBankRes()            {}
func (*R400) deleteCurrencyRateRes()    {}
func (*R400) deleteOfferRes()           {}
func (*R400) listBankCurrencyRatesRes() {}
func (*R400) listBankOffersRes()        {}
func (*R400) listBankRes()              {}
func (*R400) listCurrencyRateRes()      {}
func (*R400) listOfferRes()             {}
func (*R400) readBankRes()              {}
func (*R400) readCurrencyRateBankRes()  {}
func (*R400) readCurrencyRateRes()      {}
func (*R400) readOfferBankRes()         {}
func (*R400) readOfferRes()             {}
func (*R400) updateBankRes()            {}
func (*R400) updateCurrencyRateRes()    {}
func (*R400) updateOfferRes()           {}

type R404 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R404) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R404) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R404) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R404) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R404) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R404) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R404) deleteBankRes()            {}
func (*R404) deleteCurrencyRateRes()    {}
func (*R404) deleteOfferRes()           {}
func (*R404) listBankCurrencyRatesRes() {}
func (*R404) listBankOffersRes()        {}
func (*R404) listBankRes()              {}
func (*R404) listCurrencyRateRes()      {}
func (*R404) listOfferRes()             {}
func (*R404) readBankRes()              {}
func (*R404) readCurrencyRateBankRes()  {}
func (*R404) readCurrencyRateRes()      {}
func (*R404) readOfferBankRes()         {}
func (*R404) readOfferRes()             {}
func (*R404) updateBankRes()            {}
func (*R404) updateCurrencyRateRes()    {}
func (*R404) updateOfferRes()           {}

type R409 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R409) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R409) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R409) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R409) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R409) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R409) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R409) createBankRes()            {}
func (*R409) createCurrencyRateRes()    {}
func (*R409) createOfferRes()           {}
func (*R409) deleteBankRes()            {}
func (*R409) deleteCurrencyRateRes()    {}
func (*R409) deleteOfferRes()           {}
func (*R409) listBankCurrencyRatesRes() {}
func (*R409) listBankOffersRes()        {}
func (*R409) listBankRes()              {}
func (*R409) listCurrencyRateRes()      {}
func (*R409) listOfferRes()             {}
func (*R409) readBankRes()              {}
func (*R409) readCurrencyRateBankRes()  {}
func (*R409) readCurrencyRateRes()      {}
func (*R409) readOfferBankRes()         {}
func (*R409) readOfferRes()             {}
func (*R409) updateBankRes()            {}
func (*R409) updateCurrencyRateRes()    {}
func (*R409) updateOfferRes()           {}

type R500 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R500) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R500) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R500) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R500) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R500) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R500) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R500) createBankRes()            {}
func (*R500) createCurrencyRateRes()    {}
func (*R500) createOfferRes()           {}
func (*R500) deleteBankRes()            {}
func (*R500) deleteCurrencyRateRes()    {}
func (*R500) deleteOfferRes()           {}
func (*R500) listBankCurrencyRatesRes() {}
func (*R500) listBankOffersRes()        {}
func (*R500) listBankRes()              {}
func (*R500) listCurrencyRateRes()      {}
func (*R500) listOfferRes()             {}
func (*R500) readBankRes()              {}
func (*R500) readCurrencyRateBankRes()  {}
func (*R500) readCurrencyRateRes()      {}
func (*R500) readOfferBankRes()         {}
func (*R500) readOfferRes()             {}
func (*R500) updateBankRes()            {}
func (*R500) updateCurrencyRateRes()    {}
func (*R500) updateOfferRes()           {}

type UpdateBankReq struct {
	Name          OptString `json:"name"`
	Country       OptString `json:"country"`
	Website       OptString `json:"website"`
	LogoURL       OptString `json:"logo_url"`
	Test          OptString `json:"test"`
	CurrencyRates []int     `json:"currency_rates"`
	Offers        []int     `json:"offers"`
}

// GetName returns the value of Name.
func (s *UpdateBankReq) GetName() OptString {
	return s.Name
}

// GetCountry returns the value of Country.
func (s *UpdateBankReq) GetCountry() OptString {
	return s.Country
}

// GetWebsite returns the value of Website.
func (s *UpdateBankReq) GetWebsite() OptString {
	return s.Website
}

// GetLogoURL returns the value of LogoURL.
func (s *UpdateBankReq) GetLogoURL() OptString {
	return s.LogoURL
}

// GetTest returns the value of Test.
func (s *UpdateBankReq) GetTest() OptString {
	return s.Test
}

// GetCurrencyRates returns the value of CurrencyRates.
func (s *UpdateBankReq) GetCurrencyRates() []int {
	return s.CurrencyRates
}

// GetOffers returns the value of Offers.
func (s *UpdateBankReq) GetOffers() []int {
	return s.Offers
}

// SetName sets the value of Name.
func (s *UpdateBankReq) SetName(val OptString) {
	s.Name = val
}

// SetCountry sets the value of Country.
func (s *UpdateBankReq) SetCountry(val OptString) {
	s.Country = val
}

// SetWebsite sets the value of Website.
func (s *UpdateBankReq) SetWebsite(val OptString) {
	s.Website = val
}

// SetLogoURL sets the value of LogoURL.
func (s *UpdateBankReq) SetLogoURL(val OptString) {
	s.LogoURL = val
}

// SetTest sets the value of Test.
func (s *UpdateBankReq) SetTest(val OptString) {
	s.Test = val
}

// SetCurrencyRates sets the value of CurrencyRates.
func (s *UpdateBankReq) SetCurrencyRates(val []int) {
	s.CurrencyRates = val
}

// SetOffers sets the value of Offers.
func (s *UpdateBankReq) SetOffers(val []int) {
	s.Offers = val
}

type UpdateCurrencyRateReq struct {
	Currency OptString  `json:"currency"`
	Rate     OptFloat64 `json:"rate"`
	Bank     OptInt     `json:"bank"`
}

// GetCurrency returns the value of Currency.
func (s *UpdateCurrencyRateReq) GetCurrency() OptString {
	return s.Currency
}

// GetRate returns the value of Rate.
func (s *UpdateCurrencyRateReq) GetRate() OptFloat64 {
	return s.Rate
}

// GetBank returns the value of Bank.
func (s *UpdateCurrencyRateReq) GetBank() OptInt {
	return s.Bank
}

// SetCurrency sets the value of Currency.
func (s *UpdateCurrencyRateReq) SetCurrency(val OptString) {
	s.Currency = val
}

// SetRate sets the value of Rate.
func (s *UpdateCurrencyRateReq) SetRate(val OptFloat64) {
	s.Rate = val
}

// SetBank sets the value of Bank.
func (s *UpdateCurrencyRateReq) SetBank(val OptInt) {
	s.Bank = val
}

type UpdateOfferReq struct {
	Type        OptString `json:"type"`
	Description OptString `json:"description"`
	Link        OptString `json:"link"`
	Bank        OptInt    `json:"bank"`
}

// GetType returns the value of Type.
func (s *UpdateOfferReq) GetType() OptString {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *UpdateOfferReq) GetDescription() OptString {
	return s.Description
}

// GetLink returns the value of Link.
func (s *UpdateOfferReq) GetLink() OptString {
	return s.Link
}

// GetBank returns the value of Bank.
func (s *UpdateOfferReq) GetBank() OptInt {
	return s.Bank
}

// SetType sets the value of Type.
func (s *UpdateOfferReq) SetType(val OptString) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *UpdateOfferReq) SetDescription(val OptString) {
	s.Description = val
}

// SetLink sets the value of Link.
func (s *UpdateOfferReq) SetLink(val OptString) {
	s.Link = val
}

// SetBank sets the value of Bank.
func (s *UpdateOfferReq) SetBank(val OptInt) {
	s.Bank = val
}
