// Code generated by ent, DO NOT EDIT.

package banktranslation

import (
	"mybanks-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLTE(FieldID, id))
}

// BankID applies equality check predicate on the "bank_id" field. It's identical to BankIDEQ.
func BankID(v int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldBankID, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldLocale, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldDescription, v))
}

// BankIDEQ applies the EQ predicate on the "bank_id" field.
func BankIDEQ(v int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldBankID, v))
}

// BankIDNEQ applies the NEQ predicate on the "bank_id" field.
func BankIDNEQ(v int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNEQ(FieldBankID, v))
}

// BankIDIn applies the In predicate on the "bank_id" field.
func BankIDIn(vs ...int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldIn(FieldBankID, vs...))
}

// BankIDNotIn applies the NotIn predicate on the "bank_id" field.
func BankIDNotIn(vs ...int) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNotIn(FieldBankID, vs...))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContainsFold(FieldLocale, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BankTranslation {
	return predicate.BankTranslation(sql.FieldContainsFold(FieldDescription, v))
}

// HasBank applies the HasEdge predicate on the "bank" edge.
func HasBank() predicate.BankTranslation {
	return predicate.BankTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BankTable, BankColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBankWith applies the HasEdge predicate on the "bank" edge with a given conditions (other predicates).
func HasBankWith(preds ...predicate.Bank) predicate.BankTranslation {
	return predicate.BankTranslation(func(s *sql.Selector) {
		step := newBankStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BankTranslation) predicate.BankTranslation {
	return predicate.BankTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BankTranslation) predicate.BankTranslation {
	return predicate.BankTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BankTranslation) predicate.BankTranslation {
	return predicate.BankTranslation(sql.NotPredicates(p))
}
