// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"mybanks-api/ent/bank"
	"mybanks-api/ent/banktranslation"
	"mybanks-api/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BankTranslationQuery is the builder for querying BankTranslation entities.
type BankTranslationQuery struct {
	config
	ctx        *QueryContext
	order      []banktranslation.OrderOption
	inters     []Interceptor
	predicates []predicate.BankTranslation
	withBank   *BankQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*BankTranslation) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BankTranslationQuery builder.
func (btq *BankTranslationQuery) Where(ps ...predicate.BankTranslation) *BankTranslationQuery {
	btq.predicates = append(btq.predicates, ps...)
	return btq
}

// Limit the number of records to be returned by this query.
func (btq *BankTranslationQuery) Limit(limit int) *BankTranslationQuery {
	btq.ctx.Limit = &limit
	return btq
}

// Offset to start from.
func (btq *BankTranslationQuery) Offset(offset int) *BankTranslationQuery {
	btq.ctx.Offset = &offset
	return btq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (btq *BankTranslationQuery) Unique(unique bool) *BankTranslationQuery {
	btq.ctx.Unique = &unique
	return btq
}

// Order specifies how the records should be ordered.
func (btq *BankTranslationQuery) Order(o ...banktranslation.OrderOption) *BankTranslationQuery {
	btq.order = append(btq.order, o...)
	return btq
}

// QueryBank chains the current query on the "bank" edge.
func (btq *BankTranslationQuery) QueryBank() *BankQuery {
	query := (&BankClient{config: btq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := btq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(banktranslation.Table, banktranslation.FieldID, selector),
			sqlgraph.To(bank.Table, bank.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, banktranslation.BankTable, banktranslation.BankColumn),
		)
		fromU = sqlgraph.SetNeighbors(btq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BankTranslation entity from the query.
// Returns a *NotFoundError when no BankTranslation was found.
func (btq *BankTranslationQuery) First(ctx context.Context) (*BankTranslation, error) {
	nodes, err := btq.Limit(1).All(setContextOp(ctx, btq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{banktranslation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (btq *BankTranslationQuery) FirstX(ctx context.Context) *BankTranslation {
	node, err := btq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BankTranslation ID from the query.
// Returns a *NotFoundError when no BankTranslation ID was found.
func (btq *BankTranslationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(1).IDs(setContextOp(ctx, btq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{banktranslation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (btq *BankTranslationQuery) FirstIDX(ctx context.Context) int {
	id, err := btq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BankTranslation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BankTranslation entity is found.
// Returns a *NotFoundError when no BankTranslation entities are found.
func (btq *BankTranslationQuery) Only(ctx context.Context) (*BankTranslation, error) {
	nodes, err := btq.Limit(2).All(setContextOp(ctx, btq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{banktranslation.Label}
	default:
		return nil, &NotSingularError{banktranslation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (btq *BankTranslationQuery) OnlyX(ctx context.Context) *BankTranslation {
	node, err := btq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BankTranslation ID in the query.
// Returns a *NotSingularError when more than one BankTranslation ID is found.
// Returns a *NotFoundError when no entities are found.
func (btq *BankTranslationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(2).IDs(setContextOp(ctx, btq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{banktranslation.Label}
	default:
		err = &NotSingularError{banktranslation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (btq *BankTranslationQuery) OnlyIDX(ctx context.Context) int {
	id, err := btq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BankTranslations.
func (btq *BankTranslationQuery) All(ctx context.Context) ([]*BankTranslation, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryAll)
	if err := btq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BankTranslation, *BankTranslationQuery]()
	return withInterceptors[[]*BankTranslation](ctx, btq, qr, btq.inters)
}

// AllX is like All, but panics if an error occurs.
func (btq *BankTranslationQuery) AllX(ctx context.Context) []*BankTranslation {
	nodes, err := btq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BankTranslation IDs.
func (btq *BankTranslationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if btq.ctx.Unique == nil && btq.path != nil {
		btq.Unique(true)
	}
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryIDs)
	if err = btq.Select(banktranslation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (btq *BankTranslationQuery) IDsX(ctx context.Context) []int {
	ids, err := btq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (btq *BankTranslationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryCount)
	if err := btq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, btq, querierCount[*BankTranslationQuery](), btq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (btq *BankTranslationQuery) CountX(ctx context.Context) int {
	count, err := btq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (btq *BankTranslationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryExist)
	switch _, err := btq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (btq *BankTranslationQuery) ExistX(ctx context.Context) bool {
	exist, err := btq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BankTranslationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (btq *BankTranslationQuery) Clone() *BankTranslationQuery {
	if btq == nil {
		return nil
	}
	return &BankTranslationQuery{
		config:     btq.config,
		ctx:        btq.ctx.Clone(),
		order:      append([]banktranslation.OrderOption{}, btq.order...),
		inters:     append([]Interceptor{}, btq.inters...),
		predicates: append([]predicate.BankTranslation{}, btq.predicates...),
		withBank:   btq.withBank.Clone(),
		// clone intermediate query.
		sql:  btq.sql.Clone(),
		path: btq.path,
	}
}

// WithBank tells the query-builder to eager-load the nodes that are connected to
// the "bank" edge. The optional arguments are used to configure the query builder of the edge.
func (btq *BankTranslationQuery) WithBank(opts ...func(*BankQuery)) *BankTranslationQuery {
	query := (&BankClient{config: btq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	btq.withBank = query
	return btq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BankID int `json:"bank_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BankTranslation.Query().
//		GroupBy(banktranslation.FieldBankID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (btq *BankTranslationQuery) GroupBy(field string, fields ...string) *BankTranslationGroupBy {
	btq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BankTranslationGroupBy{build: btq}
	grbuild.flds = &btq.ctx.Fields
	grbuild.label = banktranslation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BankID int `json:"bank_id,omitempty"`
//	}
//
//	client.BankTranslation.Query().
//		Select(banktranslation.FieldBankID).
//		Scan(ctx, &v)
func (btq *BankTranslationQuery) Select(fields ...string) *BankTranslationSelect {
	btq.ctx.Fields = append(btq.ctx.Fields, fields...)
	sbuild := &BankTranslationSelect{BankTranslationQuery: btq}
	sbuild.label = banktranslation.Label
	sbuild.flds, sbuild.scan = &btq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BankTranslationSelect configured with the given aggregations.
func (btq *BankTranslationQuery) Aggregate(fns ...AggregateFunc) *BankTranslationSelect {
	return btq.Select().Aggregate(fns...)
}

func (btq *BankTranslationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range btq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, btq); err != nil {
				return err
			}
		}
	}
	for _, f := range btq.ctx.Fields {
		if !banktranslation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if btq.path != nil {
		prev, err := btq.path(ctx)
		if err != nil {
			return err
		}
		btq.sql = prev
	}
	return nil
}

func (btq *BankTranslationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BankTranslation, error) {
	var (
		nodes       = []*BankTranslation{}
		_spec       = btq.querySpec()
		loadedTypes = [1]bool{
			btq.withBank != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BankTranslation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BankTranslation{config: btq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(btq.modifiers) > 0 {
		_spec.Modifiers = btq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, btq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := btq.withBank; query != nil {
		if err := btq.loadBank(ctx, query, nodes, nil,
			func(n *BankTranslation, e *Bank) { n.Edges.Bank = e }); err != nil {
			return nil, err
		}
	}
	for i := range btq.loadTotal {
		if err := btq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (btq *BankTranslationQuery) loadBank(ctx context.Context, query *BankQuery, nodes []*BankTranslation, init func(*BankTranslation), assign func(*BankTranslation, *Bank)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BankTranslation)
	for i := range nodes {
		fk := nodes[i].BankID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bank.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bank_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (btq *BankTranslationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := btq.querySpec()
	if len(btq.modifiers) > 0 {
		_spec.Modifiers = btq.modifiers
	}
	_spec.Node.Columns = btq.ctx.Fields
	if len(btq.ctx.Fields) > 0 {
		_spec.Unique = btq.ctx.Unique != nil && *btq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, btq.driver, _spec)
}

func (btq *BankTranslationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(banktranslation.Table, banktranslation.Columns, sqlgraph.NewFieldSpec(banktranslation.FieldID, field.TypeInt))
	_spec.From = btq.sql
	if unique := btq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if btq.path != nil {
		_spec.Unique = true
	}
	if fields := btq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, banktranslation.FieldID)
		for i := range fields {
			if fields[i] != banktranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if btq.withBank != nil {
			_spec.Node.AddColumnOnce(banktranslation.FieldBankID)
		}
	}
	if ps := btq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := btq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := btq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := btq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (btq *BankTranslationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(btq.driver.Dialect())
	t1 := builder.Table(banktranslation.Table)
	columns := btq.ctx.Fields
	if len(columns) == 0 {
		columns = banktranslation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if btq.sql != nil {
		selector = btq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if btq.ctx.Unique != nil && *btq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range btq.predicates {
		p(selector)
	}
	for _, p := range btq.order {
		p(selector)
	}
	if offset := btq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := btq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BankTranslationGroupBy is the group-by builder for BankTranslation entities.
type BankTranslationGroupBy struct {
	selector
	build *BankTranslationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (btgb *BankTranslationGroupBy) Aggregate(fns ...AggregateFunc) *BankTranslationGroupBy {
	btgb.fns = append(btgb.fns, fns...)
	return btgb
}

// Scan applies the selector query and scans the result into the given value.
func (btgb *BankTranslationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, btgb.build.ctx, ent.OpQueryGroupBy)
	if err := btgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BankTranslationQuery, *BankTranslationGroupBy](ctx, btgb.build, btgb, btgb.build.inters, v)
}

func (btgb *BankTranslationGroupBy) sqlScan(ctx context.Context, root *BankTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(btgb.fns))
	for _, fn := range btgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*btgb.flds)+len(btgb.fns))
		for _, f := range *btgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*btgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := btgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BankTranslationSelect is the builder for selecting fields of BankTranslation entities.
type BankTranslationSelect struct {
	*BankTranslationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bts *BankTranslationSelect) Aggregate(fns ...AggregateFunc) *BankTranslationSelect {
	bts.fns = append(bts.fns, fns...)
	return bts
}

// Scan applies the selector query and scans the result into the given value.
func (bts *BankTranslationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bts.ctx, ent.OpQuerySelect)
	if err := bts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BankTranslationQuery, *BankTranslationSelect](ctx, bts.BankTranslationQuery, bts, bts.inters, v)
}

func (bts *BankTranslationSelect) sqlScan(ctx context.Context, root *BankTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bts.fns))
	for _, fn := range bts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
