// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MyBank-Go-Backend/ent/currencyrate"
	"MyBank-Go-Backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CurrencyRateDelete is the builder for deleting a CurrencyRate entity.
type CurrencyRateDelete struct {
	config
	hooks    []Hook
	mutation *CurrencyRateMutation
}

// Where appends a list predicates to the CurrencyRateDelete builder.
func (crd *CurrencyRateDelete) Where(ps ...predicate.CurrencyRate) *CurrencyRateDelete {
	crd.mutation.Where(ps...)
	return crd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crd *CurrencyRateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, crd.sqlExec, crd.mutation, crd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (crd *CurrencyRateDelete) ExecX(ctx context.Context) int {
	n, err := crd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crd *CurrencyRateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(currencyrate.Table, sqlgraph.NewFieldSpec(currencyrate.FieldID, field.TypeInt))
	if ps := crd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, crd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	crd.mutation.done = true
	return affected, err
}

// CurrencyRateDeleteOne is the builder for deleting a single CurrencyRate entity.
type CurrencyRateDeleteOne struct {
	crd *CurrencyRateDelete
}

// Where appends a list predicates to the CurrencyRateDelete builder.
func (crdo *CurrencyRateDeleteOne) Where(ps ...predicate.CurrencyRate) *CurrencyRateDeleteOne {
	crdo.crd.mutation.Where(ps...)
	return crdo
}

// Exec executes the deletion query.
func (crdo *CurrencyRateDeleteOne) Exec(ctx context.Context) error {
	n, err := crdo.crd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{currencyrate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crdo *CurrencyRateDeleteOne) ExecX(ctx context.Context) {
	if err := crdo.Exec(ctx); err != nil {
		panic(err)
	}
}
