// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mybanks-api/ent/bank"
	"mybanks-api/ent/offer"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Offer is the model entity for the Offer schema.
type Offer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OfferQuery when eager-loading is set.
	Edges        OfferEdges `json:"edges"`
	bank_offers  *int
	selectValues sql.SelectValues
}

// OfferEdges holds the relations/edges for other nodes in the graph.
type OfferEdges struct {
	// Bank holds the value of the bank edge.
	Bank *Bank `json:"bank,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// BankOrErr returns the Bank value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfferEdges) BankOrErr() (*Bank, error) {
	if e.Bank != nil {
		return e.Bank, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bank.Label}
	}
	return nil, &NotLoadedError{edge: "bank"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Offer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case offer.FieldID:
			values[i] = new(sql.NullInt64)
		case offer.FieldType, offer.FieldDescription, offer.FieldLink:
			values[i] = new(sql.NullString)
		case offer.ForeignKeys[0]: // bank_offers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Offer fields.
func (o *Offer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case offer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		case offer.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				o.Type = value.String
			}
		case offer.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				o.Description = value.String
			}
		case offer.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				o.Link = value.String
			}
		case offer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field bank_offers", value)
			} else if value.Valid {
				o.bank_offers = new(int)
				*o.bank_offers = int(value.Int64)
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Offer.
// This includes values selected through modifiers, order, etc.
func (o *Offer) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// QueryBank queries the "bank" edge of the Offer entity.
func (o *Offer) QueryBank() *BankQuery {
	return NewOfferClient(o.config).QueryBank(o)
}

// Update returns a builder for updating this Offer.
// Note that you need to call Offer.Unwrap() before calling this method if this Offer
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Offer) Update() *OfferUpdateOne {
	return NewOfferClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Offer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Offer) Unwrap() *Offer {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Offer is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Offer) String() string {
	var builder strings.Builder
	builder.WriteString("Offer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	builder.WriteString("type=")
	builder.WriteString(o.Type)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(o.Description)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(o.Link)
	builder.WriteByte(')')
	return builder.String()
}

// Offers is a parsable slice of Offer.
type Offers []*Offer
