// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mybanks-api/ent/banktranslation"
	"mybanks-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	banktranslationFields := schema.BankTranslation{}.Fields()
	_ = banktranslationFields
	// banktranslationDescLocale is the schema descriptor for locale field.
	banktranslationDescLocale := banktranslationFields[1].Descriptor()
	// banktranslation.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	banktranslation.LocaleValidator = banktranslationDescLocale.Validators[0].(func(string) error)
}
