// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bank is the predicate function for bank builders.
type Bank func(*sql.Selector)

// BankTranslation is the predicate function for banktranslation builders.
type BankTranslation func(*sql.Selector)

// CurrencyRate is the predicate function for currencyrate builders.
type CurrencyRate func(*sql.Selector)

// Offer is the predicate function for offer builders.
type Offer func(*sql.Selector)
